# fly.toml file generated for lightsats on 2022-10-12T14:48:18+07:00

app = "lightsats"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NEXT_PUBLIC_OVERRIDE_THEME_USERID = "cl97vjfam0000iaf662tt3em8"
    NEXT_PUBLIC_SHOW_PRODUCTION_LINK = "true"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
